# docker-compose.yml

version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel_network

    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_network

    webserver:
        image: nginx:alpine
        container_name: webserver
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        depends_on:
            - app
        networks:
            - laravel_network

    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        ports:
            - "8080:8080"
        volumes:
            - jenkins_data:/var/jenkins_home
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    db_data:
    jenkins_data:
