version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel_network

    db:
        image: postgres:latest
        container_name: my-postgres
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_USER: myuser
            POSTGRES_DB: laravel
        volumes:
            - my-postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel_network

    webserver:
        image: nginx:alpine
        container_name: webserver
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        depends_on:
            - app
        networks:
            - laravel_network

    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        ports:
            - "8080:8080"
        volumes:
            - jenkins_data:/var/jenkins_home
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    db_data:
    jenkins_data:
    my-postgres-data:
